name: generate

on:
  workflow_call:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/setup-go
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Generate code
        run: go generate ./... && git diff --exit-code
