name: release

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
        description: The next semantic version to release
      use-goreleaser:
        type: boolean
        required: false
        default: false
        description: Use GoReleaser to create a release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create tag (if not already exists)
        run: |
          git rev-parse refs/tags/${{ inputs.version }} &> /dev/null || \
          (git tag ${{ inputs.version }} && git push origin ${{ inputs.version }})

      - name: Generate changelog
        run: |
          latest=$(git describe --tags --abbrev=0)
          git log --format="* %h %s" $latest..HEAD > changelog.txt

      - name: Create release
        if: ${{ !inputs.use-goreleaser }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{ inputs.version }} --verify-tag --notes-file=changelog.txt

      # https://github.com/actions/setup-go
      - name: Set up Go
        if: ${{ inputs.use-goreleaser }}
        uses: actions/setup-go@v4
        with:
          go-version: stable

      # https://github.com/goreleaser/goreleaser-action
      - name: Create release (via GoReleaser)
        if: ${{ inputs.use-goreleaser }}
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean --release-notes=changelog.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
