name: release

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
        description: The next semantic version to release
      use-goreleaser:
        type: boolean
        required: false
        default: false
        description: Use GoReleaser to create a release
    secrets:
      HOMEBREW_TAP_TOKEN:
        required: false
        description: A token with the write permission for the `homebrew-tap` repository (required when using GoReleaser)

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create tag (if not already exists)
        run: |
          git rev-parse refs/tags/${{ inputs.version }} &> /dev/null || \
          (git tag ${{ inputs.version }} && git push origin ${{ inputs.version }})

      - name: Generate changelog
        run: |
          # 1. get the previous tag or the first commit (if there are no tags yet).
          previous=$(git describe --tags --abbrev=0 ${{ inputs.version }}~1 2> /dev/null || git rev-list --max-parents=0 HEAD)
          # 2. format the log, filter features and fixes, write a changelog file.
          git log --format="* %h %s" $previous..${{ inputs.version }} | grep -E "feat|fix" | tee changelog.txt
          # 3. add it to .gitignore since goreleaser doesn't like git in a dirty state.
          echo changelog.txt >> .git/info/exclude

      - name: Create release
        if: ${{ !inputs.use-goreleaser }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{ inputs.version }} --verify-tag --notes-file=changelog.txt

      # https://github.com/actions/setup-go
      - name: Set up Go
        if: ${{ inputs.use-goreleaser }}
        uses: actions/setup-go@v5
        with:
          go-version: stable

      # https://github.com/goreleaser/goreleaser-action
      - name: Create release (via GoReleaser)
        if: ${{ inputs.use-goreleaser }}
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean --release-notes=changelog.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
