name: test

on:
  workflow_call:
    inputs:
      go-versions:
        type: string
        required: false
        default: '[ oldstable, stable ]'
        description: Go versions to test against (JSON array)

jobs:
  test:
    strategy:
      matrix:
        go: ${{ fromJSON(inputs.go-versions) }}
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/setup-go
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: go test -v -race -shuffle=on -coverprofile=coverage.out ./...

      # https://github.com/codecov/codecov-action
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: coverage.out
