name: test

on:
  workflow_call:
    inputs:
      # arrays are not supported yet, so we use `string` + `fromJSON` as a temporarily workaround;
      # see https://github.com/orgs/community/discussions/11692 for details.
      runs-on:
        type: string
        required: false
        default: '[ "ubuntu-latest" ]'
        description: OSes to run tests on (JSON array)
      go-versions:
        type: string
        required: false
        default: '[ "oldstable", "stable" ]'
        description: Go versions to test against (JSON array)

jobs:
  test:
    strategy:
      matrix:
        os: ${{ fromJSON(inputs.runs-on) }}
        go: ${{ fromJSON(inputs.go-versions) }}
    runs-on: ${{ matrix.os }}
    steps:
      # https://github.com/actions/setup-go
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        # do not use `=` to join flags and values, it won't work on Windows;
        # see https://github.com/PowerShell/PowerShell/issues/6291 for details.
        run: go test -v -race -shuffle on -coverprofile coverage.out ./...

      # https://github.com/codecov/codecov-action
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: coverage.out
