name: vuln

on:
  workflow_call:

jobs:
  vuln:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v5

      # https://github.com/golang/govulncheck-action
      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
